import os
import logging

CONCURRENT_FETCH_LIMIT = int(os.environ.get('STORAGE_BOX_CONCURRENT_FETCH_LIMIT', '30'))
__DEFAULT_LOGGING_LEVEL_STR = os.environ.get('STORAGE_BOX_LOGGING_LEVEL', 'WARNING')
assert __DEFAULT_LOGGING_LEVEL_STR in [
    'CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG'
]
DEFAULT_LOGGING_LEVEL = getattr(logging, __DEFAULT_LOGGING_LEVEL_STR)
MAX_ALLOWED_ITEM_SIZE = 400
MAX_ALLOWED_BATCH_SIZE = 25
BATCH_ADDITION_BACKOFF_TIME = 1

